### ISSUE TITLE
Use AshOban for background jobs

### ISSUE THREAD

**Issue by kagure-nyakio** [3Stones-io/omedis#297]
Replace the send email background jobs with AshOban.

https://hexdocs.pm/ash_oban/getting-started-with-ash-oban.html#setting-up-ashoban
https://elixirforum.com/t/sending-email-as-part-of-an-action/66203/3

**Comment by amos-kibet** [comment]
Hey @almirsarajcic, I have some blockers and would love to have a call with you to figure them out. Let me know when you'll be available.

**Comment by almirsarajcic** [comment]
@wintermeyer, I was wrong. As you mentioned, this adds a scheduler that checks records every minute and triggers jobs.

I thought it would just be a different syntax for achieving the same.
So we shouldn't go this route. What we already have is better.
