### ISSUE TITLE
Create WIKI pages

### ISSUE THREAD

**Issue by fradarr** [3Stones-io/omedis#324]
#323 
Git workflow #311

**Comment by almirsarajcic** [comment]
@kagure-nyakio, please go through the list Denis has posted as well as open discussions, and add that content to the existing and new wiki pages.
Don't just post links to these discussions. Copy and edit the content where appropriate.

**Comment by almirsarajcic** [comment]
@kagure-nyakio, what's the status of this?

**Comment by kagure-nyakio** [comment]
Done.

**Comment by almirsarajcic** [comment]
Since ChatGPT did most of the work with the existing content as a reference, this shouldn't have taken 2 weeks to complete. It's really only 2 hours of work max.
