### ISSUE TITLE
Refactor code for fetching latest group and project in today live

### ISSUE THREAD

**Issue by kagure-nyakio** [3Stones-io/omedis#369]
I noticed that the code for fetching the latest group and project in today live is not efficient.
```elixir
defp latest_group_for_an_organisation(organisation, current_user) do
    case Group.by_organisation_id(%{organisation_id: organisation.id},
           actor: current_user,
           tenant: organisation
         ) do
      {:ok, %{results: groups}} ->
        Enum.min_by(groups, & &1.created_at)

      _ ->
        %{
          id: ""
        }
    end
  end
```
Instead of fetching the organisations and going through the list(remember going through lists is a 0(n) operation) to check for the newest date, it will be better to create a DB query to fetch the recently updated organisation group.

The second clause above(when no group is found) will also raise an error when one tries to access the page with the URL .../today?group_id=&project_id=proj_id. Instead, we can create a flash message informing a user to create a group before proceeding.

**Comment by almirsarajcic** [comment]
@amos-kibet, @kagure-nyakio, please don't assign yourselves until you've already finished your current tasks.
Assigning yourself before that blocks the other person from working on a task.
