### ISSUE TITLE
Implement infinite scrolling on the sticky TimeTracker menu

### ISSUE THREAD

**Issue by amos-kibet** [3Stones-io/omedis#373]
The TimeTracker introduced on #317 has a dropdown with a max height of about 224px. If there are more activities than the height can accommodate, a vertical scroll is created. We can improve this by only showing a fixed number of activities, and as the user scrolls to the bottom of the list, we fetch more. 

![Image](https://github.com/user-attachments/assets/beccd273-a2ff-48e9-aea1-5d2cf486460e)

We can use cursor-based pagination for this, and maybe a LiveView hook to detect user scroll position.

Here are examples of such an implementation:

- https://github.com/optimumBA/ash_poc/blob/main/ash_blog/assets/js/hooks/infinite_scroll_hook.js
- https://github.com/optimumBA/ash_poc/blob/e6a9dfd3abdc04c484c34e3b35e0c63b2e791e89/ash_blog/lib/ash_blog/posts/post.ex#L16
- https://github.com/optimumBA/ash_poc/blob/e6a9dfd3abdc04c484c34e3b35e0c63b2e791e89/ash_blog/lib/ash_blog_web/live/post_live/index.ex#L60C1-L86C4

**Comment by amos-kibet** [comment]
I believe this should be in the backlog, as it won't be ready until #317 gets merged into main.

**Comment by almirsarajcic** [comment]
Feel free to move the items in such cases.
Now, it's ready, though.
