### ISSUE TITLE
Cannot register a user in an empty database

### ISSUE THREAD

**Issue by almirsarajcic** [3Stones-io/omedis#382]
In an empty database without seeds, the user can't register for an account because the form requires the user to pick an organisation. Obviously, this is a problem because we're supposed to create a new organisation, not use an existing one.

![Image](https://github.com/user-attachments/assets/93a88c37-3f9f-415f-be98-680ff2524735)

**Comment by kagure-nyakio** [comment]
Should this be split into a multi-step sign-up flow?
First user registers, then we present a form for filling in their organisation data.

**Comment by kagure-nyakio** [comment]
There are 2 changesets involved so I thought splitting up the steps would be easier. 
Plus looking at it from a UX point of view, won't the form be too big ?

**Comment by almirsarajcic** [comment]
Let's look at it only from the UI/UX perspective.
We need Oghogho for this.

**Comment by Happiartista** [comment]
Adding everything in one form is going to overwhelm a user. We can have it in two steps like Nyakio suggested (Personal details and organization details) and even add a progress indicator so the user can see they can there's not much steps left to access their dashboard. Daily start/end time should be part of the organization details form

**Comment by almirsarajcic** [comment]
Thanks.
Ok, you can work together with Nyakio on that.

**Comment by Happiartista** [comment]
@almirsarajcic Awesome, really helpful, thanks.

**Comment by kagure-nyakio** [comment]
@Happiartista , how should we handle daily_start_at and daily_end_at for the user? In the current flow, we use the organisation's defaults and allow the user to change them if they want to. The only idea that comes to mind is to have this only on the organisation form in the sign up flow(as suggested above ) and enable a user to change this in their settings(user profile) after registration. Do we need a way to inform users that they can do this after signing up?

**Comment by Happiartista** [comment]
@kagure-nyakio your suggestion works. A tooltip can be useful here to inform a first time user

**Comment by kagure-nyakio** [comment]
@Happiartista , @almirsarajcic, @wintermeyer, I have also discovered that the form for creating an organization is also very long, requiring a lot of details that can be left out and filled in later from a settings page. From the attributes of the organisation's resource, only 6 fields are required, the rest can be nullable. (Required: Name, Street, Zip Code, Country, City, Timezone  + Default start and end times). Can we have the form with only these fields and leave out the rest to be filled as part of the User/Organisation Profile Settings? This way we avoid having this extra large form on sign-up:

https://github.com/user-attachments/assets/817b04e0-9110-4cda-9e52-e95b3a219503

**Comment by wintermeyer** [comment]
I totally agree with @kagure-nyakio but @DenisMGojak has to make this call.

**Comment by almirsarajcic** [comment]
Switch the organisation field to a text input that is prefilled with the user's full name.

**Comment by almirsarajcic** [comment]
@kagure-nyakio, what's the status of this?
