### ISSUE TITLE
Setup new project

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#390]
We lost the old project entries while moving the repo to https://github.com/3Stones-io/omedis

Please fix this manually. Here's a screenshot of the old project:

<img width="1442" alt="Bildschirmfoto 2024-11-26 um 09 46 15" src="https://github.com/user-attachments/assets/090d2b6d-6c80-486c-9c22-5cf46e4c7163">

**Comment by almirsarajcic** [comment]
Added all the issues available in the repo.
