### ISSUE TITLE
Set up automatic activities creation on user registration

### ISSUE THREAD

**Issue by almirsarajcic** [3Stones-io/omedis#392]
When organisation gets created, we should automatically an activity:
- Miscellaneous

Similar to #391 and #278.

**Comment by almirsarajcic** [comment]
@amos-kibet, sorry, we've changed the requirement. We only need one default activity.

**Comment by amos-kibet** [comment]
Noted, also, I believe it should depend on #391, because a project is needed in order to create the activity.

**Comment by almirsarajcic** [comment]
In such cases, maybe move the task to the Backlog because it's blocked.
I forgot about that relationship.
