### ISSUE TITLE
Update invitation user ID when invited user creates an account

### ISSUE THREAD

**Issue by amos-kibet** [3Stones-io/omedis#404]
When an invited user registers,  associate their user account with their invitation record.

**Comment by amos-kibet** [comment]
I have a challenge of figuring out how to update the invitation.user_id field when the invited user registers. Here are the options I have tried but have not worked:

Added a hidden invitation_id form input so I can use after_action hook to update the invitation:
```elixir
authentication do
    strategies do
      password :password do
        identity_field :email

        sign_in_tokens_enabled? true
        confirmation_required?(false)

        register_action_accept([
          :current_organisation_id,
          :email,
          :first_name,
          :last_name,
          :gender,
          :birthdate,
          :lang,
          :daily_start_at,
          :daily_end_at
        ])
      end
    end
```
This does not work because invitation_id is not an attribute of the User resource, and there's no way I can pass it as an argument to this action used for user registration
Also, the action used for user registration does not seem to allow using `after_action` changes.

I haven't figured out a way to get hold of the registered user's ID so I can update the related invitation.

If we prevent user from changing the email when registering via invitation, I might find a solution, but we let users change email, so this won't work.

@almirsarajcic, @wintermeyer let me know what ideas you have.

**Comment by wintermeyer** [comment]
Have you asked the question in the https://elixirforum.com ? I do think this is a problem others might run into too and there for it helps everyone to ask for help.

**Comment by almirsarajcic** [comment]
I wouldn't rely on the hidden input as it's a security hole. We do have UUIDs so we would achieve security through obscurity, but still I don't think it's a good practice.

For the `after_action` part, I agree with Stefan - you should ask in ElixirForum. Regardless of the way you decide to approach this issue, this might help other people.

For the email field, maybe we should disable the input anyway. The owner will invite their coworkers using work email, so maybe they shouldn't be able to change it. I think that would be enough for the first version. We can change it later if we want to.

**Comment by amos-kibet** [comment]
I got help, here is my question: https://elixirforum.com/t/using-ash-changes-in-ashauthentication-strategy-password-registration-action/67756

**Comment by amos-kibet** [comment]
I created this global `changes` in the `User` resource:
```elixir
changes do
    change {Omedis.Accounts.User.Changes.AssociateUserWithInvitation, []} do
      where [action_is(:register_with_password)]
    end
```

with the change module looking like this:

```elixir
def change(%{attributes: %{email: email}} = changeset, _opts, _context) do
    IO.inspect(changeset, label: "[CHANGE 11]", limit: :infinity, pretty: true)

    Ash.Changeset.after_action(changeset, fn
      _changeset, user ->
        maybe_update_invitation(email, user.id)
        |> IO.inspect(label: "[AFTER_ACTION]", limit: :infinity, pretty: true)

        {:ok, user}

      other, another ->
        IO.inspect(other, label: "[OTHER]", limit: :infinity, pretty: true)
        IO.inspect(another, label: "[ANOTHER]", limit: :infinity, pretty: true)

        :not_sure_what_to_return_here
    end)
    |> IO.inspect(label: "[CHANGE 20]", limit: :infinity, pretty: true)
  end
```

I get the logs, **[CHANGE 11]** and **[CHANGE 20]**, but not any of **[AFTER_ACTION]**, **OTHER** & **ANOTHER**. Basically, it seems code execution does not get to the body of my `after_action` hook.  I don't know why, but it means I can't update the invitation this way.

I could not figure this out on Friday, so I went with using PubSub and a singleton GenServer that updates invitations everytime it receives the PubSub.

**Comment by wintermeyer** [comment]
I guess you are going to change the `IO.inspect` to some sort of logging, right?

**Comment by amos-kibet** [comment]
> I guess you are going to change the `IO.inspect` to some sort of logging, right?

When it's ready, I'll get rid of the logs, I don't think they are necessary, and we don't create them in the codebase either. But if you mean using Logger for debugging, I did that, but got into the same issue as well.

**Comment by almirsarajcic** [comment]
I guess don't mark answers on ElixirForum as solved until you're sure the solution works.
Subsequent comments usually go ignored there.

**Comment by wintermeyer** [comment]
> I guess don't mark answers on ElixirForum as solved until you're sure the solution works.

We have all been there! You can uncheck the answer and mark an other one as the right one.

**Comment by almirsarajcic** [comment]
Notes from the meeting:

- make sure also the status gets updated
- use https://github.com/ash-project/ash_state_machine to manage status
