### ISSUE TITLE
Investigate possibility of automating Project workflows

### ISSUE THREAD

**Issue by almirsarajcic** [3Stones-io/omedis#417]

**Comment by almirsarajcic** [comment]
Also find a solution for status updates.

**Comment by almirsarajcic** [comment]
Besides the [built-in automations](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-built-in-automations), there is an option of creation custom ones:

- [Using the API to manage Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects) (official)
- [https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions](https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions) (official)
- [How to Use GitHub Actions to Automate Open-Source Projects](https://www.freecodecamp.org/news/automate-open-source-projects-with-github-actions/) (freecodecamp)

I'll check how much work is involved and do the first attempt.

**Comment by almirsarajcic** [comment]
@wintermeyer mentioned we might also want to merge PRs automatically when the checks pass.

Stefan, please write down other ideas for automation so I can try to complete them all at once.

**Comment by almirsarajcic** [comment]
@wintermeyer, I'll need enforced permissions in the GitHub organization so I can create a GitHub App and install it to this repo. In the meantime, I'll experiment with a temporary org and a repo.

Just for future reference, since I haven't worked with workflows for anything other than CI/CD pipeline, I've asked Cursor and Claude to figure this out for me.

> I want to set up project automation workflow for @https://github.com/orgs/3Stones-io/projects/3/views/13 
> You should create a new yml file under .github/workflows for that.
> 
> These are the things I want to accomplish:
> - when a developer moves an issue from Ready to In Progress column, the following shoud happen:
>   - that developer should be assigned to the issue
>   - start date should be set to today
>   - a new branch should be created for the issue, so that when PR gets created, it will be automatically linked to that issue
> - when a developer requests a review:
>   - if all the checks passed, the linked issue should be moved from In Progress to the In Review column
> - when a reviewer requests changes:
>   - the linked issue should be moved from In Review to In Progress
> 
> Context:
> @https://github.com/3Stones-io/omedis/issues/417 
> @https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-built-in-automations 
> @https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects 
> @https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions 
> @https://www.freecodecamp.org/news/automate-open-source-projects-with-github-actions/ 

Besides the code snippet I'll try somewhere, I've got the following answer:

> You'll need to:
> 1. Create a GitHub App with necessary permissions:
>   - Issues: Read/Write
>   - Pull Requests: Read/Write
>   - Projects: Read/Write
>   - Contents: Read/Write (for branch creation)
> 2. Store the App ID as APP_ID in repository variables
> 3. Store the private key as APP_PEM in repository secrets
> 4. Update the field IDs and option IDs in the GraphQL queries to match your project's configuration
> 
> The workflow handles:
> - Card moves to In Progress:
>   - Assigns the mover as assignee
>   - Sets start date
>   - Creates and pushes a new branch
> - PR review requested:
>   - Checks if all checks passed
>   - Moves to In Review if checks passed
> - Changes requested:
>   - Moves back to In Progress
> 
> Let me know if you need help with any specific part or want to add additional functionality.

**Comment by almirsarajcic** [comment]
By the way, I just saw that there's a Project template here on GitHub that has the current and the next iteration views. I think that's exactly what @DenisMGojak means when saying MVP1, MVP2, etc.

![Image](https://github.com/user-attachments/assets/cb7251f8-15c1-441d-9713-595eb17e0238)
![Image](https://github.com/user-attachments/assets/55111535-7efd-40fb-b3f6-1504eeea737d)

In the project settings, there is an option to set up iterations and their duration.

![Image](https://github.com/user-attachments/assets/53445cc7-796e-4382-ab88-544c649b6bf9)

But we're not there yet. For that, we'd need a lot more workload. I guess for now, milestones suffice.

**Comment by DenisMGojak** [comment]
This is exactly that, wow, cool … Thanks for digging and finding this!

**Comment by wintermeyer** [comment]
> By the way, I just saw that there's a Project template here on GitHub that has the current and the next iteration views

I like it too! We could use 6 week timeframes.

**Comment by almirsarajcic** [comment]
I foolishly believed Claude and tried with GitHub Actions approach.
It didn't work. There are no events related to projects triggering GitHub Actions workflows, it was all a dream.

There is an alternative, though: webhooks.
I'll try to implement a simple app handling these events. If it takes more than a few hours, I don't think it will be worth it. If I fail, as a backup I've created two views that I check regularly to see if I missed adding required info:
- https://github.com/orgs/3Stones-io/projects/3/views/11
- https://github.com/orgs/3Stones-io/projects/3/views/12

**Comment by wintermeyer** [comment]
In case @almirsarajcic can really pull this off within a couple of hours it could become a very nice and for many projects useful side project which we should host as a separate GitHub repo. A minimal Rails application which automate the stuff we need. I am pretty sure other's would appreciate this.

**Comment by wintermeyer** [comment]
Did I write Rails? 😱 Must be muscle memory. I meant Phoenix/Elixir.

**Comment by almirsarajcic** [comment]
Played around a bit with the great help of Cursor, Claude, GitHub API docs, Neuron, Tentacat...
And here's the result:

https://github.com/user-attachments/assets/e4dbd831-ee73-4bdd-8774-45e0fc3665fb

- moving the ticket to the "In progress" column
  - sets the assignee to the current user
  - sets the start date to the current date
- requesting a review (for a PR linked to an issue)
  - moves the ticket to the "In review" column
- requesting changes
  - moves the ticket back to the "In progress" column
- closing the issue (moving it to the "Done" column)
  - sets the end date to the current date

I decided not to create a branch when moving to the "In progress" column. Initially, I thought it would automatically link the PR, but after some experimentation, I realized we didn't get that benefit while it restricted us by enforcing a branch name (freedom of speech mentioned 😁). Also, I decided not to wait for the workflow to finish before moving the linked ticket to the "In review" column. I'm not sure whether we should do that. Anyway, this is just the initial implementation. We can improve it in future iterations.

It works even when multiple issues are linked to a single PR - all issues will be updated. It's not in the screen recording, but trust me™.

The code is available at https://github.com/3Stones-io/bean_counter.

Tomorrow, I'll:
- [ ] remove the debugging code
- [ ] refactor a tiny bit
- [ ] deploy with Kamal to the staging server

I'll probably need help from @wintermeyer to set it up with our org: create a GitHub app and install it in our org.

**Comment by wintermeyer** [comment]
> I'll probably need help from @wintermeyer to set it up with our org: create a GitHub app and install it in our org.

@almirsarajcic Let's tackle that together on Monday. I just sent you an invitation.

**Comment by almirsarajcic** [comment]
Finished setting up the server.
On Monday we can set up a new app and then update environment variables.
Currently, it's set up to work with https://github.com/orgs/AlmirTestOrg/projects/3 which I used for testing.

**Comment by almirsarajcic** [comment]
I've set it up with the current repo.

As I mentioned, it's far from perfect, so there will be plenty of room for improvement, including fixing intermittent issues.
