### ISSUE TITLE
Hide validation messages for inputs not yet focused

### ISSUE THREAD

**Issue by amos-kibet** [3Stones-io/omedis#421]
Issue noted on #415, where validation messages are appearing for fields that have not been focused yet.

**Comment by almirsarajcic** [comment]
Please share a screen recording of the behavior so everyone has more context on the issue.
We were kinda rushing, so we forgot to add that.

Here's some context: https://hexdocs.pm/phoenix_live_view/changelog.html#migrating-from-phx-feedback-for
We're using phoenix_live_view 1.0.0-rc.7 in this project, so we don't have the shims and we need to add them.

**Comment by amos-kibet** [comment]
https://github.com/user-attachments/assets/fc5b48ef-4ed2-4c9c-abfe-a67b9a8c9164

**Comment by almirsarajcic** [comment]
It doesn't work for multiple issues, or it might need a comma instead of an ampersand. 🤷
Anyway, thanks!
