### ISSUE TITLE
Invitees should not create an organisation after invitation

### ISSUE THREAD

**Issue by kagure-nyakio** [3Stones-io/omedis#424]
@almirsarajcic, @wintermeyer, I noticed that in the current flow, when an invitee accepts an invitation and creates an account, they still have access to create an organisation. There is a rule that only one organisation per user can be created, and the invitee already belongs to an organisation. I think that this is a bug.

https://github.com/user-attachments/assets/3555a2b0-8256-46af-a6c8-85ff503f16e1

**Comment by almirsarajcic** [comment]
Good catch!
