### ISSUE TITLE
Today's Time Tracker repeated in sidebar

### ISSUE THREAD

**Issue by amos-kibet** [3Stones-io/omedis#437]
The link to **Today's Time Tracker** is repeated in the sidebar, as shown below. The second link works, while the first one doesn't. 
<img width="390" alt="Image" src="https://github.com/user-attachments/assets/2c51c5ec-40c9-4ef8-ac09-fff28f75d6a4" />

One of them should be removed, but since the current organisation link sits between them, we need to know which of the two should be removed. @wintermeyer, which link should be removed?

**Comment by wintermeyer** [comment]
Please remove the not working link.

PS: We have to do some housekeeping GUI wise anyway.
