### ISSUE TITLE
Users without first and/or last name

### ISSUE THREAD

**Issue by amos-kibet** [3Stones-io/omedis#443]
I just created a user account from an invitation, and got redirected to `/edit_profile` page, with a form to fill first and last name. I did not fill that; ignored them and clicked on other parts of the application. Now, in the section where I should see my name, it's blank:

https://github.com/user-attachments/assets/06a3f53e-6c1d-45bf-b492-0b1f90887de8

Should we have some default username, which would be used in cases like this?

cc @almirsarajcic @wintermeyer

**Comment by almirsarajcic** [comment]
I think we should use the user's email address as a backup for when the name is `nil`.

If we force the user to fill their profile on the `/edit_profile`, then it beats the purpose of having them skip name and other info during the registration.

**Comment by wintermeyer** [comment]
I like the `.to_s` approach in the Ruby on Rails world. An object has a `.to_s` method which gets called. This converts that object into a string. We can do something similar within Phoenix by adding a `to_s` function/helper to a resource and call that. So in the future, when we want to change this we can change it in one place.

**Comment by almirsarajcic** [comment]
https://hexdocs.pm/elixir/1.12/String.Chars.html

**Comment by kagure-nyakio** [comment]
@wintermeyer, wrote the explanation for `to_string` here: https://github.com/3Stones-io/omedis/wiki/Polymorphism-with-Protocols

**Comment by wintermeyer** [comment]
> @wintermeyer, wrote the explanation for `to_string` here: https://github.com/3Stones-io/omedis/wiki/Polymorphism-with-Protocols

WOW! Nice work! Please add one small example which shows the use of it in a HEEX context. Just so that everybody who uses this every day gets it right way. Maybe even start with this to hook the reader.
