### ISSUE TITLE
Fix demo and persona seeds

### ISSUE THREAD

**Issue by kagure-nyakio** [3Stones-io/omedis#452]
Running demo and persona seeds crashes.
To complete the fix, look for changes made in `maybe_create_organisation.ex`, `create_organisation_defaults.ex`, and `add_invited_user_to_invitation_groups.ex`.

**Comment by kagure-nyakio** [comment]
@almirsarajcic , in personas_seeds should there be three organisations or just one organisation belonging to user `denis.gojak@spitex-bemeda.ch` who invites the others?

**Comment by almirsarajcic** [comment]
@kagure-nyakio, everything clear? Need help with something?
